Use typing.Dict instead of dict for type hints
Resolves error when running tests on python 3.8:
TypeError: type object is not subscriptable
See https://stackoverflow.com/q/59101121 for more